blank_issues_enabled: true
contact_links:
  - name: Community Channels / 社区渠道
    url: https://docs.astrbot.app/community.html
    about: Join our community, share your experience, and get support. / 加入我们的社区，与其他用户交流经验、获取支持。
  - name: Upload Plugin / 提交插件
    url: https://cloud.astrbot.app
    about: Go to AstrBot Cloud to submit a plugin. / 前往 AstrBot 市场提交插件。
